version: '3.8'
services:
  neo4j:
    image: neo4j:5.21.0
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j-data/data:/data
    environment:
      NEO4J_PLUGINS: '["apoc"]'